prometheus: # Tool name
  github: https://github.com/prometheus/prometheus # Publich Tool repo
  internalRepo: # Internal repo which contains some values.yaml file
  slack:
    enabled: true # If you'd like to receive some slack notification
    tag: # Who tag in slack message (keep empty if noone tag: [])
      - team # Slack group to tag 
      - UXXXXXXX # Slack User Id to tag
  autoMR:
    enabled: true # Automatically create MR to masterBranch if new version is detected
    masterBranch: main # To which branch create MR/PR if new version is detected
    projectId: 00000000 # Mandatory for gitlab (Gitlab projectId)
    repoName: prometheus # Mandatory for github/bitbucket (repository name)
    owner: pannoi # Mandatory for github/bitbucket (Owner name: usually organisation)
  version:
    - file: base/prometheus-prometheus.yaml # values.yaml file with specified version
      yamlPath: spec.version # Yaml path where version specified in file