prometheus: # Tool name
  github: https://github.com/prometheus/prometheus # Public Tool repo
  internalRepo: # Internal repo which contains some values.yaml file
  slack:
    enabled: true # If you'd like to receive some slack notification
    tag: # Who tag in slack message (keep empty if noone tag: [])
      - team # Slack group to tag 
      - UXXXXXXX # Slack User Id to tag
  autoMR:
    enabled: true # Automatically create MR to masterBranch if new version is detected
    masterBranch: main # To which branch create MR/PR if new version is detected
    deleteBranch: true # Optional, set `true` if you'd like to delete src branch after merge (If not set => false)
    projectId: 00000000 # Mandatory for gitlab (Gitlab projectId)
    repoName: prometheus # Mandatory for github/bitbucket (repository name)
    owner: pannoi # Mandatory for github/bitbucket (Owner name: usually organisation)
  version:
    - file: base/prometheus-prometheus.yaml # values.yaml file with specified version
      yamlPath: spec.version # Yaml path where version specified in file
mimir:
  github: https://github.com/grafana/mimir # Public Tool repo
  internalRepo: # Internal repo which contains some values.yaml file
  helmChart: operations/helm/charts/mimir-distributed/Chart.yaml # Optional
  slack:
    enabled: true # If you'd like to receive some slack notification
    tag: # Who tag in slack message (keep empty if noone tag: [])
      - team # Slack group to tag 
      - UXXXXXXX # Slack User Id to tag
  autoMR:
    enabled: true # Automatically create MR to masterBranch if new version is detected
    deleteBranch: false # Optional, set `true` if you'd like to delete src branch after merge (If not set => false)
    masterBranch: main # To which branch create MR/PR if new version is detected
    projectId: 00000000 # Mandatory for gitlab
    repoName: prometheus # Mandatory for github/bitbucket (repository name)
    owner: pannoi # Mandatory for github/bitbucket (Owner name: usually organisation)
  chart: # Needed only if helmChart specified
    - file: overlays/kustomization.yaml # File where is specified helm chart version
      yamlPath: helmCharts[0].version # Yaml path to where is chart version specified
grafana:
  github: https://github.com/grafana/grafana # Publich Tool repo
  internalRepo: # Internal repo which contains some values.yaml file
  slack:
    enabled: true
    tag: # Who tag in slack message (keep empty if noone tag: [])
      - team # Slack group to tag 
      - UXXXXXXX # Slack User Id to tag
  autoMR:
    enabled: true # If you'd like to receive some slack notification
    masterBranch: main # To which branch create MR/PR if new version is detected
    projectId: 00000000 # Mandatory for gitlab
    repoName: prometheus # Mandatory for github/bitbucket (repository name)
    owner: pannoi # Mandatory for github/bitbucket (Owner name: usually organisation)
  version:
    - file: base/grafana-deployment.yaml # values.yaml file with specified version
      yamlPath: spec.template.spec.containers[0].image # Yaml path where version specified in file
